//! Parity with CantinaOS's Python router on the recorded corpus and a synthetic answer set
//! (both generated by running `jev_intents.decide` - see tests/data/*.json).

use r3x_intent::*;
use serde_json::Value;
use std::path::PathBuf;
use std::sync::Arc;
use std::time::Duration;

fn repo() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../..")
}
fn data(name: &str) -> Vec<Value> {
    serde_json::from_str(&std::fs::read_to_string(PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/data").join(name)).unwrap()).unwrap()
}
fn close(a: f64, b: &Value) -> bool {
    (a - b.as_f64().unwrap()).abs() < 1e-9
}

fn check(d: &RouterDecision, want: &Value, ctx: &str) {
    assert_eq!(d.intent.as_deref(), want["intent"].as_str(), "{ctx}: {}", d.reason);
    if d.intent.is_some() {
        assert_eq!(Value::Object(d.parameters.clone()), want["parameters"], "{ctx}");
    }
    assert_eq!(d.tier, want["tier"].as_str().unwrap(), "{ctx}");
    assert!(close(d.confidence, &want["confidence"]), "{ctx}: {} vs {}", d.confidence, want["confidence"]);
}

/// Our request is byte-identical to CantinaOS's (every recorded key is hit), and the decision
/// on each recorded answer equals Python's at two thresholds.
#[tokio::test]
async fn recorded_corpus_matches_python() {
    let mut fixtures = std::collections::HashMap::new();
    for corpus in ["smoke-voice", "smoke-show"] {
        fixtures.insert(corpus, JevClient::replay(Arc::new(JevFixtures::load(repo().join("fixtures").join(corpus), 0.0).unwrap())));
    }
    let q = catalogue::build_questions();
    let cases = data("python_decisions.json");
    assert!(cases.len() >= 16);
    for c in &cases {
        let utt = c["utterance"].as_str().unwrap();
        let client = &fixtures[c["corpus"].as_str().unwrap()];
        let r = client.classify(&catalogue::build_state(utt), &q).await.unwrap_or_else(|| panic!("fixture key miss for {utt:?}"));
        let thr = c["threshold"].as_f64().unwrap();
        check(&decide(Some(&r), utt, thr, 0.5), c, utt);
    }
}

#[test]
fn synthetic_answers_match_python() {
    #[derive(serde::Deserialize)]
    struct Raw {
        answers: Box<serde_json::value::RawValue>,
    }
    let text = std::fs::read_to_string(PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/data/python_synthetic.json")).unwrap();
    let raws: Vec<Raw> = serde_json::from_str(&text).unwrap();
    let cases = data("python_synthetic.json");
    let mut fired = 0;
    for (i, c) in cases.iter().enumerate() {
        let body = format!(r#"{{"model": "jev-1.13.0", "answers": {}}}"#, raws[i].answers.get());
        let r = JevResult::from_json(&body, 0.0).unwrap();
        let d = decide(Some(&r), c["utterance"].as_str().unwrap(), c["threshold"].as_f64().unwrap(), c["command_threshold"].as_f64().unwrap());
        check(&d, c, &format!("case {i}"));
        let top: Vec<String> = serde_json::from_value(c["top_two"].clone()).unwrap();
        assert_eq!(d.top_two(), top, "case {i}");
        fired += d.intent.is_some() as usize;
    }
    assert!(fired >= 15, "synthetic set exercises dispatches too ({fired})");
    assert!(decide(None, "x", 0.85, 0.5).intent.is_none());
}

#[tokio::test]
async fn speculation_hits_and_clears_per_turn() {
    let fx = Arc::new(JevFixtures::load(repo().join("fixtures/smoke-voice"), 0.0).unwrap());
    let cfg = RouterConfig { api_key: "replay".into(), ..Default::default() };
    let router = IntentRouter::new(JevClient::replay(fx), cfg);
    assert!(router.active());
    router.turn_started();
    router.partial("stop", false); // one word: ignored
    router.partial("stop the music", true);
    tokio::time::sleep(Duration::from_millis(50)).await;
    let out = router.classify_turn("stop the music").await;
    assert!(out.speculative_hit);
    assert_eq!(out.decision.intent.as_deref(), Some("stop_music"));

    router.turn_started(); // cache cleared: a live (replayed) call now
    let out = router.classify_turn("stop the music").await;
    assert!(!out.speculative_hit && out.result.is_some());

    // an unrecorded utterance fails open to the Claude path
    let out = router.classify_turn("never recorded").await;
    assert!(out.result.is_none() && out.decision.intent.is_none());
}

#[tokio::test]
#[ignore = "spends API credit"]
async fn live_jev_classifies_a_command() {
    let env = std::fs::read_to_string(repo().join(".env")).unwrap_or_default();
    let Some(key) = env.lines().find_map(|l| l.strip_prefix("TYPESAFE_API_KEY=")).map(|k| k.trim().trim_matches('"').to_string()) else {
        eprintln!("no TYPESAFE_API_KEY in .env; skipped");
        return;
    };
    let client = JevClient::new(&key, Duration::from_millis(1500)); // cold TLS on a one-off call
    let r = client.classify(&catalogue::build_state("stop the music"), &catalogue::build_questions()).await.expect("live Jev answered");
    let d = decide(Some(&r), "stop the music", 0.85, 0.5);
    eprintln!("jev {} in {:.0} ms -> {:?} ({})", r.model, r.latency_ms, d.intent, d.reason);
    assert_eq!(r.model, JEV_MODEL);
    assert_eq!(d.intent.as_deref(), Some("stop_music"));
}
